// <auto-generated />
namespace ArtesaniasMombacho.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingClassesAndController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingClassesAndController));
        
        string IMigrationMetadata.Id
        {
            get { return "201612031811104_AddingClassesAndController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
